package com.CasS3.Name.controllers;

import com.CasS3.Name.entities.UserLogin;
import com.CasS3.Name.services.UserLoginService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/name")
public class UserLoginController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserLoginService userLoginService;

    @CrossOrigin(origins = "http://localhost:8080/")
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody UserLogin addNewUserLogin (@RequestBody UserLogin n) {
        userLoginService.addUserLogin(n);
        return n;
    }
    @CrossOrigin(origins = "http://localhost:8080/")
    @GetMapping(path="/get")
    public @ResponseBody String getName(@RequestParam String email) {
        return userLoginService.getNameByEmail(email);
    }
}
